---
name: Text-Wrapper
version: 1.02
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
abstract: Simple word wrapping routine
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.004
build_requires:
  File::Spec: 0
  FindBin: 0
  Module::Build: 0.21
  Test::More: 0
dynamic_config: 0
provides:
  Text::Wrapper:
    file: lib/Text/Wrapper.pm
    version: 1.02
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - tools
